# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bmgr < Formula
  desc "Terminal keybinding manager with fzf"
  homepage "https://github.com/davidpanter/bmgr"
  version "0.1.0"
  license "BSD-2-Clause"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidpanter/bmgr/releases/download/v0.1.0/bmgr_darwin_amd64.tar.gz"
      sha256 "e25ce0c2c6bcb09a3a4d975cd9f65cbe9217fdf4ca7d442311b5e73a736d3bc7"

      define_method(:install) do
        bin.install "bmgr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidpanter/bmgr/releases/download/v0.1.0/bmgr_darwin_arm64.tar.gz"
      sha256 "277a83ecd2a1d2cb13546d8a67e37effe0e7f9552c4fccc7e9c22fd07ddf59f1"

      define_method(:install) do
        bin.install "bmgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidpanter/bmgr/releases/download/v0.1.0/bmgr_linux_amd64.tar.gz"
      sha256 "f6da3d3c835f2978e1f4e662a9868df49992ae53d1198a8f5f81c74535a5402e"
      define_method(:install) do
        bin.install "bmgr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidpanter/bmgr/releases/download/v0.1.0/bmgr_linux_arm64.tar.gz"
      sha256 "00966d46f6237b7f98051411a178634786186f107bf9f9214ed92381a693ae9d"
      define_method(:install) do
        bin.install "bmgr"
      end
    end
  end
end
